version: '3'

services:
  # Web server
  web: 
    build: ./web/
    volumes: 
     - ./data:/data
     - ./web/src/:/src
     - ./logs:/var/log
    ports:
      - '5000:5000'
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
    depends_on:
      - backend
      - mongo

  backend: 
    build: ./backend/
    ports:
     - '5001:5001'
    volumes: 
     - ./data:/data
     - ./backend/src:/src
     - ./logs:/var/log
     - ./backend/models:/src/models
    environment:
      - FLASK_DEBUG=${FLASK_DEBUG}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    depends_on:
      - mongo

  conquest: 
    build: ./conquest/
    tty: true
    stdin_open: true
    ports:
      - '5004:80'
    volumes: 
     - conquest-store:/src/Conquest-DICOM-Server/data

  mongo:
    image: 'mongo:6.0-jammy'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - ./data/db:/data/db
    ports:
    - '5002:27017'

  mongo-express:
    image: 'mongo-express:1.0.2'
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "5003:8081"
      
volumes:
  conquest-store: