version: '0'

services:
  web: 
    build: ./web/
    volumes: 
     - ./data:/data
     - ./web/src/:/src
     - ./logs:/var/log
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: "true"

  backend: 
    build: ./backend/
    ports:
     - "5001:5001"
    volumes: 
     - ./data:/data
     - ./backend/src:/src
     - ./logs:/var/log
     - ./backend/models:/src/models
    environment:
      FLASK_DEBUG: "true"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]